[profile.release]
opt-level = 3
lto = true
panic = 'abort'

[package]
name = "epic"
version = "0.2.1"
authors = ["Denis Memmesheimer <denismemmesheimer@gmail.com>"]

[dependencies]
regex = { version = "1" }
url = { version = "2.4.1" }
epos = { path = "../epos" }
config = "0.13"
serde = "1.0.8"